### ISSUE TITLE
[Bug]: Timeout Time does not Increase on Login

### ISSUE THREAD

**Issue by suerion** [someaddons/connectivity#101]
### Describe the bug you're experiencing

Hey, i had tried to use the newest Update. 
It looks like there is an Packet Error, but i don't get it whats the issue.

Had set the timeout timer to 300+ again, but the Timeout come again after a few seconds. will add the logs again.

Had enabled yet all debug logs and get this error with polymer mods :
[latest.log](https://github.com/user-attachments/files/17016855/latest.log)
[client-latest.log](https://github.com/user-attachments/files/17016928/client-latest.log)

```
[18:59:23] [Render thread/INFO]: Connecting to suerion.hopto.org, 25565
[19:00:00] [Netty Client IO #2/WARN]: io.netty.handler.timeout.ReadTimeoutException
[19:00:00] [Netty Client IO #2/WARN]: Network error for:packet_handler
io.netty.handler.timeout.ReadTimeoutException: null
[19:00:00] [Netty Client IO #2/ERROR]: Exception occurred in netty pipeline
io.netty.handler.timeout.ReadTimeoutException: null
[19:00:01] [Render thread/WARN]: Client disconnected with reason: Zeitüberschreitung (Timeout)
```

And it look like, the server loading is a little bit faster

here are the logs, without polymer mods: (Disabled Eldritch Mobs, Polymer and Toms Mobs): (All Package Debug errors are enabled)
On first Connection i got this debug issue 
[disconnect-2024-09-16_19.28.10-client.txt](https://github.com/user-attachments/files/17017149/disconnect-2024-09-16_19.28.10-client.txt)
Here the latest log from Server: I could join again (first Join only disconnection)
[latest.log](https://github.com/user-attachments/files/17017162/latest.log)
[client latest.log](https://github.com/user-attachments/files/17017212/client.latest.log)

If it is an Polymer issue, i will also check there, but should it not a timeout after 38s because i had increased the timeout to 300s?

Thanks for looking on this issue and https://github.com/someaddons/connectivity/issues/100

### Reproducability

Start Server with Connectivity, enable Polymer Mods, Timeout in a few seconds, timeout timer changed to 300+

Without Polymer Mods, i could join the server with Connectivity

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.21.1

### Modloader version

Fabric

### Logs

logs above

**Comment by suerion** [comment]
We had found an Polymer an issue with the custom Payload, will come back again, after we had found some fixes, to fix connectivity

**Comment by suerion** [comment]
here are the changings
https://github.com/Patbox/polymer/compare/0.9.14+1.21.1...0.9.15+1.21.1

Without Connectivity i could join the server yet without the payload error,

now connectivity give me an timeout
Client log:
https://mclo.gs/H32QVwZ
```
[23:13:19] [Netty Client IO #2/WARN]: io.netty.handler.timeout.ReadTimeoutException
[23:13:19] [Netty Client IO #2/WARN]: Network error for:packet_handler
io.netty.handler.timeout.ReadTimeoutException: null
[23:13:19] [Netty Client IO #2/ERROR]: Exception occurred in netty pipeline
io.netty.handler.timeout.ReadTimeoutException: null
[23:13:20] [Render thread/WARN]: Client disconnected with reason: Zeitüberschreitung
```
Server log:
https://mclo.gs/FaEhQ4j

**Comment by someaddons** [comment]
try 6.1

**Comment by suerion** [comment]
Hey thanks for working on @someaddons 

had on the newest version this crash, 

```
[12:24:54] [Server thread/WARN]: @Redirect conflict. Skipping connectivity.mixins.json:ConnectionMixin from mod connectivity->@Redirect::onWait(Lio/netty/channel/ChannelFuture;)Lio/netty/channel/ChannelFuture; with priority 1000, already redirected by vmp.mixins.json:networking.avoid_deadlocks.MixinClientConnection from mod vmp->@Redirect::noDisconnectWait(Lio/netty/channel/ChannelFuture;)Lio/netty/channel/ChannelFuture; with priority 1050
[12:24:54] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2535 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at knot/net.minecraft.class_3242.method_14354(class_3242.java:86) ~[server-intermediary.jar:?]
	at knot/net.minecraft.class_3176.method_3823(class_3176.java:153) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:664) ~[server-intermediary.jar:?]
	at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.9.jar:?]
	... 9 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector onWait(Lio/netty/channel/ChannelFuture;)Lio/netty/channel/ChannelFuture; in connectivity.mixins.json:ConnectionMixin from mod connectivity failed injection check, (0/1) succeeded. Scanned 0 target(s). Using refmap connectivity-fabric-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:531) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1490) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:752) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:330) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.15.4+mixin.0.8.7.jar:0.15.4+mixin.0.8.7]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.16.9.jar:?]
	... 9 more
```

https://mclo.gs/Fvcd9xI

**Comment by suerion** [comment]
@someaddons it is an incompatibilty with VMP, 

Work without VMP, will try to connect with client soon

**Comment by suerion** [comment]
https://github.com/RelativityMC/VMP-fabric

**Comment by suerion** [comment]
Got again this messages, but connectivity work fine 

```
[18:51:52 ERROR] [Netty Server IO #13]: [Connection] Exception occurred in netty pipeline
java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:401) ~[?:?]
        at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:434) ~[?:?]
        at knot/io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:254) ~[netty-buffer-4.1.97.Final.jar:?]
        at knot/io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.97.Final.jar:?]
        at knot/io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.97.Final.jar:?]
        at knot/io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.97.Final.jar:?]
        at knot/io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.97.Final.jar:?]
        at knot/io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.97.Final.jar:?]
        at knot/io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.97.Final.jar:?]
        at knot/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.97.Final.jar:?]
        at knot/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:?]
        at knot/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[18:51:52 ERROR] [Netty Server IO #13]: [PacketEncoder] Error sending packet clientbound/minecraft:disconnect
io.netty.handler.codec.EncoderException: Sending unknown packet 'clientbound/minecraft:disconnect'
        at knot/net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:47) ~[?:?]
        at knot/net.minecraft.network.codec.IdDispatchCodec.encode(IdDispatchCodec.java:14) ~[?:?]
        at knot/net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:26) ~[?:?]
        at knot/net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:12) ~[?:?]
        at knot/io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:?]
        at knot/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
        at knot/io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
        at knot/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
        at knot/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
        at knot/io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:?]
        at knot/net.minecraft.network.Connection$2.write(Connection.java:530) ~[?:?]
        at knot/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
        at knot/io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:?]
        at knot/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:?]
        at knot/io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:?]
        at knot/io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.97.Final.jar:?]
        at knot/io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.97.Final.jar:?]
        at knot/io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.97.Final.jar:?]
        at knot/net.minecraft.network.Connection.doSendPacket(Connection.java:350) ~[?:?]
        at knot/net.minecraft.network.Connection.sendPacket(Connection.java:343) ~[?:?]
        at knot/net.minecraft.network.Connection.mixinextras$bridge$method_10764$120(Connection.java) ~[?:?]
        at knot/net.minecraft.network.Connection.connectivity$wrapSend(Connection.java:776) ~[?:?]
        at knot/net.minecraft.network.Connection.wrapOperation$cgo000$connectivity$logErrorFor(Connection.java:768) ~[?:?]
        at knot/net.minecraft.network.Connection.send(Connection.java:325) ~[?:?]
        at knot/net.minecraft.network.Connection.send(Connection.java:319) ~[?:?]
        at knot/net.minecraft.network.Connection.exceptionCaught(Connection.java:170) ~[?:?]
        at knot/io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346) ~[netty-transport-4.1.97.Final.jar:?]
        at knot/io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325) ~[netty-transport-4.1.97.Final.jar:?]
        at knot/io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317) ~[netty-transport-4.1.97.Final.jar:?]
        at knot/io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1377) ~[netty-transport-4.1.97.Final.jar:?]
        at knot/io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346) ~[netty-transport-4.1.97.Final.jar:?]
        at knot/io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325) ~[netty-transport-4.1.97.Final.jar:?]
        at knot/io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:907) ~[netty-transport-4.1.97.Final.jar:?]
        at knot/io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.handleReadException(AbstractNioByteChannel.java:125) ~[netty-transport-4.1.97.Final.jar:?]
        at knot/io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:177) ~[netty-transport-4.1.97.Final.jar:?]
        at knot/io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.97.Final.jar:?]
        at knot/io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.97.Final.jar:?]
        at knot/io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.97.Final.jar:?]
        at knot/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.97.Final.jar:?]
        at knot/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:?]
        at knot/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[18:51:52 WARN] [Netty Server IO #13]: [Connectivity] Packet:net.minecraft.class_2661 caused an error above, printing name & data
[18:51:52 WARN] [Netty Server IO #13]: [Connectivity] Packet data:
"class_2661[reason=translation{key='disconnect.genericReason', args=[Internal Exception: java.net.SocketException: Connection reset]}]"
```

**Comment by suerion** [comment]
Will close this issue yet,
next ->
https://github.com/someaddons/connectivity/issues/104
