### ISSUE TITLE
[Bug]: Cleuwe lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.toString()" because "p_130086_" is null

### ISSUE THREAD

**Issue by Cleuwe222** [someaddons/connectivity#41]
### Describe the bug you're experiencing

when connecting via a local network, an error appears and does not allow access to the server. When you run a single game on this modpack, everything works.
Cleuwe lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.toString()" because "p_130086_" is null
minecraft version 1.19

### Reproducability

launched the game. I clicked connect and selected a server over a local network.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

https://gist.github.com/Cleuwe222/137012b3034d3b7384cc3cf4bc6e2dc6

**Comment by Cleuwe222** [comment]
even at startup, I found such lines in the console. Is it important

[Worker-Main-1/ERROR]: Failed to retrieve profile key pair
java.io.IOException: Could not retrieve profile key pair
	at TRANSFORMER/minecraft@1.19/net.minecraft.client.multiplayer.ProfileKeyPairManager.m_233789_(ProfileKeyPairManager.java:137)
	at TRANSFORMER/minecraft@1.19/net.minecraft.client.multiplayer.ProfileKeyPairManager.m_233796_(ProfileKeyPairManager.java:63)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by Shpikon** [comment]
Hi Cleuwe222, I think it's because of the mod.
I am facing the same problem, did you find this mod or a solution to the problem?
