### ISSUE TITLE
[Bug]: Packet is null

### ISSUE THREAD

**Issue by Dezzixr** [someaddons/connectivity#46]
### Describe the bug you're experiencing

Alright, so i want to start off saying i'm very much a complete idiot when it comes to modding. Me and my friends wanted a big kitchensink pack so i just chucked a HUGE number of mods together. Without connectivity, we get the "payload is larger than xxxx" error, but now with connectivity installed we get an error that i understand absolutely nothing about.

Sorry for the rather chaotic bug report, i'm a bit socially inept so bear with me </3 

My question is mainly.. what is causing this? 

![image](https://user-images.githubusercontent.com/72324699/206189050-6e35786a-b865-4c1e-bb3d-c782f6c95224.png)

### Reproducability

Like an idiot, chuck together a huge amount of mods, install connectivity and try to connect.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18

### Modloader version

Forge

### Logs

https://gist.github.com/Dezzixr/8a333986e25b12f918fa8a68f583d4d1

**Comment by someaddons** [comment]
Hi, I'll need the full logs of both server+client, your log just has forge's default debug packet print in it

**Comment by Dezzixr** [comment]
Hi! I'm so sorry for the late reply, i've been caught up lately </3

Here's both the client and server log. If there's anything else i can do, please let me know!
[ServerLog.txt](https://github.com/someaddons/connectivity/files/10221233/ServerLog.txt)
[ClientLog.txt](https://github.com/someaddons/connectivity/files/10221236/ClientLog.txt)

**Comment by Dezzixr** [comment]
I tried it again, this time the Client Log was a lot more obvious about the error. Check the bottom. Maybe this can be of more use to you?

The exact excerpt i'm talking about is 

java.util.NoSuchElementException: packet_handler
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073) ~[netty-all-4.1.68.Final.jar%2327!/:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:248) ~[netty-all-4.1.68.Final.jar%2327!/:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237) ~[netty-all-4.1.68.Final.jar%2327!/:4.1.68.Final]
	at net.minecraftforge.network.filters.NetworkFilters.lambda$injectIfNecessary$1(NetworkFilters.java:34) ~[forge-1.18.2-40.1.86-universal.jar%23505!/:?]
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:196) ~[guava-31.0.1-jre.jar%2329!/:?]
	at net.minecraftforge.network.filters.NetworkFilters.injectIfNecessary(NetworkFilters.java:30) ~[forge-1.18.2-40.1.86-universal.jar%23505!/:?]
	at net.minecraftforge.network.NetworkHooks.sendMCRegistryPackets(NetworkHooks.java:108) ~[forge-1.18.2-40.1.86-universal.jar%23505!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_5998_(ClientPacketListener.java:375) ~[client-1.18.2-20220404.173914-srg.jar%23500!/:?]
	at net.minecraft.network.protocol.game.ClientboundLoginPacket.m_5797_(ClientboundLoginPacket.java:83) ~[client-1.18.2-20220404.173914-srg.jar%23500!/:?]
	at net.minecraft.network.protocol.game.ClientboundLoginPacket.m_5797_(ClientboundLoginPacket.java:19) ~[client-1.18.2-20220404.173914-srg.jar%23500!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.18.2-20220404.173914-srg.jar%23500!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%23500!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220404.173914-srg.jar%23500!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%23500!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[client-1.18.2-20220404.173914-srg.jar%23500!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1015) ~[client-1.18.2-20220404.173914-srg.jar%23500!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23500!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23500!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.86.jar%2317!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]

Again, sorry if i sound like a total idiot haha.
[ClientLogNew.txt](https://github.com/someaddons/connectivity/files/10258008/ClientLogNew.txt)

**Comment by Dezzixr** [comment]
Okay! I ended up figuring out what's causing it. It seems to be an incompatibility(?) issue with Immersive Portals. As soon as i removed it, it let me log in. I would really like to use Immersive Portals though, do you have any idea what causes this issue between your mod and IP?

**Comment by Dezzixr** [comment]
I'll include another log-- It specifies that it's Immersive Portals causing the packet issue. Maybe it'll help you figure out what's causing it and how to fix it?
[2022-12-19-6.log](https://github.com/someaddons/connectivity/files/10259243/2022-12-19-6.log)

**Comment by Lolothepro** [comment]
#44 (but with Immersive Portal For Forge)

**Comment by someaddons** [comment]
I've added compat to 1.19, not gonna backport

**Comment by TotalMisplay** [comment]
> I've added compat to 1.19, not gonna backport

Hi, I found this thread after having a lot of problems all day. I see you backported 1.18.2 Immersive Portals support for Fabric. Any chance that means this has changed and we will see a backport for 1.18.2 Forge to have Immersive Portals support?
