### ISSUE TITLE
[Bug]: mod no working, fabric 1.19.2

### ISSUE THREAD

**Issue by MrJorman** [someaddons/connectivity#52]
### Describe the bug you're experiencing

![image](https://user-images.githubusercontent.com/55187962/215568310-9f7ecb80-a363-40c7-83a0-56959ec0c4bf.png)

Packet Limiter no working, i use Mod Artifacts and my server crash

### Reproducability

  "disablePacketLimits": {
    "desc:": "Should play packet size limits be disabled? Error:(Badly compressed packet) default:true",
    "disablePacketLimits": true
  },
  
  I even installed the XL Pockets mod, but it still didn't help.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

https://gist.github.com/MrJorman/aba8f13995346495aee36a53f4cff431

**Comment by itsdinkd** [comment]
Different issue but also packet unlimiter not working for a player

```java
00:13:59] [Server thread/ERROR]: Error executing task on Server
java.lang.IllegalArgumentException: Payload may not be larger than 1048576 bytes
        at net.minecraft.class_2658.<init>(class_2658.java:39) ~[server-intermediary.jar:?]
        at net.minecraft.class_1297.toComponentPacket(class_1297.java:17155) ~[server-intermediary.jar:?]
        at dev.onyxstudios.cca.api.v3.component.ComponentKey.syncWith(ComponentKey.java:196) ~[cardinal-components-base-5.0.2-f6adbaa29328b251.jar:?]
        at dev.onyxstudios.cca.api.v3.component.ComponentKey.syncWith(ComponentKey.java:189) ~[cardinal-components-base-5.0.2-f6adbaa29328b251.jar:?]
        at dev.onyxstudios.cca.internal.entity.CardinalComponentsEntity.syncEntityComponents(CardinalComponentsEntity.java:82) ~[cardinal-components-entity-5.0.2-34867dc024c90e79.jar:?]
        at dev.onyxstudios.cca.internal.entity.CardinalComponentsEntity.lambda$init$0(CardinalComponentsEntity.java:57) ~[cardinal-components-entity-5.0.2-34867dc024c90e79.jar:?]
        at net.minecraft.class_3324.handler$ccn000$onPlayerLogIn(class_3324.java:5524) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_14570(class_3324.java:249) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_33800(class_3248.java:151) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.md5f5acc$lambda$polymer_prePlayHandshakeHackfest$0$0(class_3248.java:3052) ~[server-intermediary.jar:?]
        at eu.pb4.polymer.impl.networking.EarlyConnectionMagic.lambda$handle$0(EarlyConnectionMagic.java:28) ~[polymer-0.2.18+1.19.2-cd67caaa292fd17e.jar:?]
        at eu.pb4.polymer.api.x.EarlyPlayNetworkHandler.lambda$onKeepAlive$0(EarlyPlayNetworkHandler.java:98) ~[polymer-0.2.18+1.19.2-cd67caaa292fd17e.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$cfb000$modifiedRunLoop(MinecraftServer.java:7394) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by someaddons** [comment]
Its not supposed to unlimit everything, those limits are important to expose bugs which cause too much data being sent. Report this to the mod's causing it instead
