### ISSUE TITLE
[Bug]: MC crashes, when loading into the world

### ISSUE THREAD

**Issue by Cape-City** [someaddons/connectivity#64]
### Describe the bug you're experiencing

After updating to version connectivity-fabric-1.19.3-4.0.jar, MC is crashing while loading into the world.

Yes i know - i have a lot of mods installed :D

### Reproducability

Switching Mod back to connectivity-fabric-1.19.3-3.9.jar everything is as it should be and MC loads without crashing into the world. Going back to latest version, MC crashes again.

I also tried with a fresh profile, with less mods installed. The game doesn't crashed now, but i either can't load into the world.
The error in the latest.log file is the same:

[21:59:51] [Server thread/ERROR]: Couldn't place player in world
java.lang.ClassCastException: class net.minecraft.class_2658 cannot be cast to class com.connectivity.networkstats.IPacketDataSetter (net.minecraft.class_2658 and com.connectivity.networkstats.IPacketDataSetter are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @6279cee3)
	at net.fabricmc.fabric.impl.networking.server.ServerNetworkingImpl.createPlayC2SPacket(ServerNetworkingImpl.java:534) ~[fabric-networking-api-v1-1.2.17+4017a8cb85-c6775f0d76b0775b.jar:?]
	at net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking.createS2CPacket(ServerPlayNetworking.java:211) ~[fabric-networking-api-v1-1.2.17+4017a8cb85-c6775f0d76b0775b.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.createPacket(ServerPlayNetworkAddon.java:101) ~[fabric-networking-api-v1-1.2.17+4017a8cb85-c6775f0d76b0775b.jar:?]
	at net.fabricmc.fabric.api.networking.v1.PacketSender.sendPacket(PacketSender.java:79) ~[fabric-networking-api-v1-1.2.17+4017a8cb85-c6775f0d76b0775b.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.sendInitialChannelRegistrationPacket(AbstractChanneledNetworkAddon.java:116) ~[fabric-networking-api-v1-1.2.17+4017a8cb85-c6775f0d76b0775b.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.onClientReady(ServerPlayNetworkAddon.java:67) ~[fabric-networking-api-v1-1.2.17+4017a8cb85-c6775f0d76b0775b.jar:?]
	at net.minecraft.class_3324.handler$zfn000$fabric-networking-api-v1$handlePlayerConnection(class_3324.java:2507) ~[client-intermediary.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:208) ~[client-intermediary.jar:?]
	at net.minecraft.class_3248.method_33800(class_3248.java:131) ~[client-intermediary.jar:?]
	at net.minecraft.class_3248.method_14384(class_3248.java:118) ~[client-intermediary.jar:?]
	at net.minecraft.class_3248.redirect$zfo000$fabric-networking-api-v1$handlePlayerJoin(class_3248.java:563) ~[client-intermediary.jar:?]
	at net.minecraft.class_3248.method_18784(class_3248.java:68) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:248) ~[client-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:830) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:59:51] [Server thread/INFO]: Monty_McDonnell lost connection: Invalid player data

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

https://gist.github.com/Cape-City/75497522d5a4de34c38a7203d8bef420

**Comment by Cape-City** [comment]
It has something to do with Immersive Portals. Both worlds i tested had an active nether portal with the Immersive Portals Mod.
When i loaded the world without the connectivity mod, deactivate the nether portal, acivate the connectivity mod again and
then the nether portal, MC loads into the world without any issue.

**Comment by pokesmells** [comment]
I also receive this crash on the latest version for Fabric 0.14.19

**MC Version: 1.19.2**
**Mod Version: connectivity-fabric-1.19.2-4.0**
**OS Version: Windows 11**
**Loader Type: Curseforge**

Crash log: https://mclo.gs/1f3dwEY

Latest log: https://mclo.gs/juEFkrn

**Comment by Cape-City** [comment]
It seems that it has sonething to do with the Immersive Portals mod and an active nether portal.

**Comment by pokesmells** [comment]
> It seems that it has sonething to do with the Immersive Portals mod and an active nether portal.

I don't have that mod.

**Comment by pokesmells** [comment]
This may be a different crash.

**Comment by Cape-City** [comment]
Did the downgrade of this mod also fixes your crash?

**Comment by pokesmells** [comment]
Yes

**Comment by someaddons** [comment]
fixed in 4.1

**Comment by Cape-City** [comment]
Thanx for fixing!
