### ISSUE TITLE
[Bug]: Can't join the server

### ISSUE THREAD

**Issue by sternschnaube** [someaddons/connectivity#67]
### Describe the bug you're experiencing

Couldn't place player in world
java.lang.ClassCastException: class net.minecraft.class_2658 cannot be cast to class com.connectivity.networkstats.IPacketDataSetter (net.minecraft.class_2658 and com.connectivity.networkstats.IPacketDataSetter are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @7a187f14)
	at net.fabricmc.fabric.impl.networking.server.ServerNetworkingImpl.createPlayC2SPacket(ServerNetworkingImpl.java:534) ~[fabric-networking-api-v1-1.3.1+a6f3ccfaf4-e61eadbb137ebdba.jar:?]
	at net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking.createS2CPacket(ServerPlayNetworking.java:388) ~[fabric-networking-api-v1-1.3.1+a6f3ccfaf4-e61eadbb137ebdba.jar:?]
	at net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking.send(ServerPlayNetworking.java:427) ~[fabric-networking-api-v1-1.3.1+a6f3ccfaf4-e61eadbb137ebdba.jar:?]
	at me.andre111.mambience.MAmbienceFabric.lambda$initServer$5(MAmbienceFabric.java:128) ~[Mambience-5.3.0+1.19.4-noAssets.jar:?]
	at net.fabricmc.fabric.api.networking.v1.S2CPlayChannelEvents.lambda$static$0(S2CPlayChannelEvents.java:38) ~[fabric-networking-api-v1-1.3.1+a6f3ccfaf4-e61eadbb137ebdba.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.invokeRegisterEvent(ServerPlayNetworkAddon.java:102) ~[fabric-networking-api-v1-1.3.1+a6f3ccfaf4-e61eadbb137ebdba.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.register(AbstractChanneledNetworkAddon.java:164) ~[fabric-networking-api-v1-1.3.1+a6f3ccfaf4-e61eadbb137ebdba.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.registerPendingChannels(AbstractChanneledNetworkAddon.java:72) ~[fabric-networking-api-v1-1.3.1+a6f3ccfaf4-e61eadbb137ebdba.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.<init>(ServerPlayNetworkAddon.java:50) ~[fabric-networking-api-v1-1.3.1+a6f3ccfaf4-e61eadbb137ebdba.jar:?]
	at net.minecraft.class_3244.handler$dbo001$fabric-networking-api-v1$initAddon(class_3244.java:3507) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.<init>(class_3244.java:255) ~[server-intermediary.jar:?]
	at net.minecraft.class_3324.redirect$zka000$carpet$replaceNetworkHandler(class_3324.java:4524) ~[server-intermediary.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:185) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_33800(class_3248.java:131) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_14384(class_3248.java:118) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.redirect$dbn000$fabric-networking-api-v1$handlePlayerJoin(class_3248.java:1063) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_18784(class_3248.java:68) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:254) ~[server-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:172) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:912) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:828) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zik000$carpet$modifiedRunLoop(MinecraftServer.java:18936) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:654) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[16:39:39] [Server thread/WARN]: Failed to handle packet for 
java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.handleDisconnect()" because "this.addon" is null
	at net.minecraft.class_3244.handler$dbo001$fabric-networking-api-v1$handleDisconnection(class_3244.java:3521) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_10839(class_3244.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10768(class_2535.java:435) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:258) ~[server-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:172) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:912) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:828) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zik000$carpet$modifiedRunLoop(MinecraftServer.java:18936) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:654) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[16:39:39] [Server thread/WARN]: handleDisconnection() called twice
[16:39:42] [Raknetify Epoll #2/INFO]: [STDERR]: PLAY java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.impl.networking.AbstractNetworkAddon.handleDisconnect()" because the return value of "net.fabricmc.fabric.impl.networking.NetworkHandlerExtensions.getAddon()" is null

### Reproducability

Installed Connectivity on client and server. Having it just on client makes no problems.
I was connecting via Raknet connection: https://github.com/RelativityMC/raknetify

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

/

**Comment by someaddons** [comment]
fixed in 4.1

**Comment by sternschnaube** [comment]
Thanks!
